/** Place details fields grouped by category, as accepted by the Places API v1 field mask. */
export const FIELD_CATEGORIES: Record<string, string[]> = {
  'Basic Information': [
    'formattedAddress',
    'addressComponents',
    'location',
    'displayName',
    'name',
    'shortFormattedAddress',
    'adrFormatAddress',
  ],
  'Ratings & Reviews': ['rating', 'userRatingCount', 'reviews', 'editorialSummary'],
  'Business Details': [
    'businessStatus',
    'currentOpeningHours',
    'regularOpeningHours',
    'priceLevel',
    'priceRange',
    'types',
    'primaryType',
    'primaryTypeDisplayName',
  ],
  'Contact Information': [
    'websiteUri',
    'internationalPhoneNumber',
    'nationalPhoneNumber',
    'googleMapsUri',
    'googleMapsLinks',
  ],
  'Dining Options': [
    'delivery',
    'dineIn',
    'takeout',
    'reservable',
    'servesBeer',
    'servesWine',
    'servesCocktails',
    'servesDessert',
    'servesDinner',
    'servesLunch',
  ],
  Amenities: [
    'outdoorSeating',
    'liveMusic',
    'menuForChildren',
    'goodForChildren',
    'goodForGroups',
    'goodForWatchingSports',
    'allowsDogs',
    'restroom',
  ],
  'Location Details': ['plusCode', 'viewport', 'timeZone', 'utcOffsetMinutes', 'addressDescriptor'],
  'Media & Content': ['photos'],
  Services: ['parkingOptions', 'paymentOptions', 'accessibilityOptions'],
};

export const DEFAULT_SELECTED_FIELDS = [
  'formattedAddress',
  'addressComponents',
  'location',
  'displayName',
  'rating',
  'userRatingCount',
];

/** Primary types covering addresses, locations, and geographic places (no businesses). */
export const PLACES_ONLY_TYPES = [
  'locality',
  'sublocality',
  'street_address',
  'route',
  'geocode',
  'premise',
  'neighborhood',
  'postal_code',
  'administrative_area_level_1',
  'administrative_area_level_2',
  'administrative_area_level_3',
  'administrative_area_level_4',
  'administrative_area_level_5',
  'administrative_area_level_6',
  'administrative_area_level_7',
  'sublocality_level_1',
  'sublocality_level_2',
  'sublocality_level_3',
  'sublocality_level_4',
  'sublocality_level_5',
  'postal_town',
  'postal_code_prefix',
  'postal_code_suffix',
  'intersection',
  'plus_code',
  'political',
  'natural_feature',
  'archipelago',
  'colloquial_area',
  'continent',
  'town_square',
  'subpremise',
];
